---
virtualmachines:
  - name: "satellite"
    image: "satellite-server-rhdp-6-17-06-13-25"
    bootloader: efi
    register_satellite: false
    memory: "32G"
    cores: 4
    image_size: "540G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
      - name: satellite-https
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: satellite-https
    routes:
      - name: satellite-https
        host: satellite
        service: satellite-https
        targetPort: 443
        tls: true
        tls_termination: reencrypt
        tls_destinationCACertificate: |
          -----BEGIN CERTIFICATE-----
          MIIGyTCCBLGgAwIBAgIUZPQwm28Gh5V2T/aZvVelkHZYRB4wDQYJKoZIhvcNAQEL
          BQAweDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYD
          VQQHDAdSYWxlaWdoMRAwDgYDVQQKDAdLYXRlbGxvMRQwEgYDVQQLDAtTb21lT3Jn
          VW5pdDEWMBQGA1UEAwwNc2F0ZWxsaXRlLmxhYjAeFw0yNTA2MTMxNjQ3MDZaFw0z
          ODAxMTcxNjQ3MDZaMHgxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJv
          bGluYTEQMA4GA1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHS2F0ZWxsbzEUMBIGA1UE
          CwwLU29tZU9yZ1VuaXQxFjAUBgNVBAMMDXNhdGVsbGl0ZS5sYWIwggIiMA0GCSqG
          SIb3DQEBAQUAA4ICDwAwggIKAoICAQC5avfCtHGpQ8u8NG51KImH4nAVmamnk7XV
          GnNcd4TUImBmZHKpApTg/0U3yzi7IOPTMJr20a2J8aV7ln2dFm09C6RCmX/j6DaZ
          9nYGpQiJ71mVWyf5U3ZWRoTZB80E3n+vBWQZywTgGk59cBTbAIdu2K+XUql16exa
          psiB3m0glbZk5ZQSjJxvOiwbQhuThk+ZJCnD8xhJJf9ZOlw8KHob1aN7SKCP7NQS
          H/FTmB3c4ZixnvjPiDSNMjFyViMgMTGQLAK9Rn9V0a7tMIGttCeSh5WmXgWT9k7N
          sWIR0Q4kJBSevyFhFKKfeO1v3V+B3Z/0VDwKWd46Q8deWSEWIsMKrw2Ix89Q/ba9
          ZkWF3RSYwfQ2MjuYsFhcCytCs05eviK9ROG+PFye6dQGzZKVGrs6+OkAM+awiioo
          n+O/dLFArt5c6q7puemfxcC0Q9DSaR/n3WwZKHqI3mYCzu5CzVyXPpUa/pKFCJt/
          AGY++KhgM8+KYVqzf0+nNssRDpkp8/hiPV9uMFcW+RBHjAuIgAk/JXlXudaHci/g
          gNPkSHAKiUvxi/bKgGMYBfGyCQ7i+De4BZxTFuPXF8pAoCjKstiVqXdntib5S2EY
          dvU0XPBeg+oVIHrsZfyct5yyDjwxV5iF0pmK1GlYI8Kn1cgO10ODx/PeoDqfZkAl
          ZYBI3u5lnQIDAQABo4IBSTCCAUUwDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMCAaYw
          HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMBEGCWCGSAGG+EIBAQQEAwIC
          RDA1BglghkgBhvhCAQ0EKBYmS2F0ZWxsbyBTU0wgVG9vbCBHZW5lcmF0ZWQgQ2Vy
          dGlmaWNhdGUwHQYDVR0OBBYEFOjBiNX5PCHp5w7n9wd/6u3/jJhuMIGfBgNVHSME
          gZcwgZShfKR6MHgxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGlu
          YTEQMA4GA1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHS2F0ZWxsbzEUMBIGA1UECwwL
          U29tZU9yZ1VuaXQxFjAUBgNVBAMMDXNhdGVsbGl0ZS5sYWKCFGT0MJtvBoeVdk/2
          mb1XpZB2WEQeMA0GCSqGSIb3DQEBCwUAA4ICAQA2pxqcZzAOD2nvx3O8ZVuvbasb
          0bZzFF2zrjTVaUFkDwkhAXL5PCfcs/740OCsrFPSrzE5r7VIvb06t7X3mfn0Iw9N
          1h9jkQMk4sjNGzG3F0Q24uPDmuPZiuaqBTB1uvCnGjYpQH29yDKx0OFWLqhfYLHt
          c0Z9aTrHKBzchJtwvf/9GWkCYxq8voH4IQ/VcfwO2iINQtSzgmxcpDoNC1J0AUCx
          yMBnCNxrVJ/28fKafgi6rblPPaFoTSIff+nuTtmUSfKuL+gfkSV/QvReWXErCJCa
          mWaf0sIQhEbQvDjvF/8kUURtf1HK/iittGTlaBYjkjN4J7Pnr81YwQZ2mu0ESdrS
          lcXxr7tnsOB+/yGz7qGVPaVQNi61zDUtIJQ9j8GV3Fwr2aetH36aXn/MxXoWccKk
          WufJrhWHldfPRU48xBih8aUHlohfGHsf6jl0bHEq8LOOJDujr1A5po9iFWf92wbn
          x2N31X0P8IiXwHG5SWjPio5gzoQkLLT4getxNETVRMTgJNXpU4Hn14oOZIqEDxaR
          zMLexMYBTiQO6mtvZo7aTL3x8hRoReJvjp0TmRBoPeyEU8lx19dE8ujVBVqq8R5a
          T80+iomU6lMVM7belMf0tl0loa/D+vjd0jfGnip+4ewbEr+dj9TAzfsCBidLrl4a
          +WTV/ogDLLZX8gj6kg==
          -----END CERTIFICATE-----
  - name: "rhel1"
    image: "rhel-10-0-06-17-25-2"
    bootloader: efi
    register_satellite: false
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
  - name: "rhel2"
    image: "rhel-10-0-06-17-25-2"
    bootloader: efi
    register_satellite: false
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
